version: '3.8'
services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "15432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
